apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: websocket-service
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}  # الدومين يأتي من values.yaml
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: {{ .Values.service.port }}
