apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # تأكد من إضافة هذا السطر
  rules:
  - host: websocket.aks.example.com  # استخدم IP خارجي مؤقتًا إذا لم يكن لديك DNS
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 8800
