apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: websocket-app
    meta.helm.sh/release-namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: websocket-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
