apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: websocket-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
