replicaCount: 1

image:
  repository: myacrHELM.azurecr.io/fastapi-websocket
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8800
  targetPort: 8800

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
