apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-websocket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-websocket-app
  template:
    metadata:
      labels:
        app: my-websocket-app
    spec:
      containers:
        - name: websocket-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8800
