name: Enable Azure Monitor for App Service

on:
  push:
    branches:
      - main

permissions:
  id-token: write 

jobs:
  enable-monitoring:
    runs-on: ubuntu-latest
    steps:
    
         # 🔹 Azure Login
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Application Insights if it doesn't exist
        run: |
          az monitor app-insights component create \
            --app myAppInsights \
            --location eastus \
            --resource-group myResourceGroupTR \
            --application-type web \
            --kind web

      - name: Link Application Insights to App Service
        run: |
          INSTRUMENTATION_KEY=$(az monitor app-insights component show \
            --app myAppInsights \
            --resource-group myResourceGroupTR \
            --query instrumentationKey \
            --output tsv)

          az webapp config appsettings set \
            --name my-fastapi-websocket-app \
            --resource-group myResourceGroupTR \
            --settings APPINSIGHTS_INSTRUMENTATIONKEY=$INSTRUMENTATION_KEY

      - name: Verify successful linkage
        run: |
          az webapp config appsettings list \
            --name my-fastapi-websocket-app \
            --resource-group myResourceGroupTR \
            --query "[?name=='APPINSIGHTS_INSTRUMENTATIONKEY']"

